version: '3'
services:
  app:
    image: openjdk:21-slim
    ports:
      - target: 8080
        published: ${HOST_PORT}
        protocol: tcp
        mode: host

    environment:
      - ACEISS_API_KEY=${ACEISS_API_KEY}
      - ACEISS_USER_LIST_REFRESH_DELAY=${ACEISS_USER_LIST_REFRESH_DELAY}
    volumes:
      - ${ACEISS_AGENT_PATH}:/agent
      - ./target/registration-login-demo-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-javaagent:/agent/aceiss-javaagent.jar", "-jar", "/app/app.jar"]
