version: "3.3"

services:
  db:
    image: arm64v8/mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Quelea99#
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=UserDB
      - MYSQL_PASSWORD=UserDB
# To get to php admin http://localhost:8081/index.php?route=/&route=%2F

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=Quelea99#


  web:
    image: tomcat:9
    volumes:
      - ./target/WebappSpringSecurity-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/WebappSpringSecurity.war
      #../../javaagent/agent/build/libs is the location of where the java agent is located.
      - ../../javaagent/agent/build/libs:/agent
    ports:
      - '8080:8080'
      - '8089:8089'
    environment:
      - MYSQL_ROOT_PASSWORD=Quelea99#
      - MYSQL_ROOT_USER=root
      - ACEISS_API_KEY=EnYi1GDvulDXYlYlTZx0xmsMV4VKVPVGcrbe_YkqdNMNMSjAt5tXXkp4-o_RWx.1V6x7JgDYf6P2Yd5sObSZry9UdrGAu6RKGakMG0e9HhjfAZ09j98Gqw8g8EenAkAcdTR13GM31j1dMLEiJWb4V7ZYdrsf373E6j1IxDDNF0SpwtdSdgYxF8t9nmCyzvJgv4TcQWn2CAGustUub6ViezUE3pQoNiUWTf4GqX3z4_LdTy2miaZiYU5sMsxGj1PMBa2aDQmdhLtAUmL2jcgSSnMcNOQErWlSOZOewsReW
      - ACEISS_API_ENDPOINT=http://192.168.1.159:4318/
      - JAVA_OPTS=-javaagent:/agent/aceiss-javaagent.jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:8089

#  otel-collector:
##    image: https://github.com/aceiss/collector/blob/main/release/aceiss-collector-windows-0.61.0.exe:latest
#    image: aceiss/collector:latest
#    command: [ "--config=/etc/config.yml" ]
#    volumes:
#      - ./config.yml:/etc/config.yml
#    ports:
#      - "4318:4318"


