version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Quelea99#
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=UserDB
      - MYSQL_PASSWORD=UserDB


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=Quelea99#


  web:
    image: tomcat:9
    volumes:
      - ./target/WebappSpringSecurity-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/WebappSpringSecurity.war
      - ./target:/agent
    ports:
      - '8082:8080'
    environment:
      - MYSQL_ROOT_PASSWORD=Quelea99#
      - MYSQL_ROOT_USER=root
      - ACEISS_API_KEY=sdfx.dcYMrPZZEzc9lhL6oUDj2P5vKDrCT1dsDxPOGzf1ARDSxQu-GixL2D8z2FwHzzj0M5uwj7NJauc4sljyu2MlwsMgrtl74oWzZb35iLLtsBWS8Uy2bQWiDRDuCT2ZVtm0sztWYiTX5ZPsMoLYpUZie2tIMpyMNU1z9La_ejxXm4oX9MDZB_L88KMUlfAjgEwcOIHX5n-jwJVwdcVuuZfDGYwFWGtk0_RtlyWFsmWa9UY6hhSIk_yFnxGNjEMxYMnRWdVmSCXJjNkF10jRWNUgFr9B4Ou7YTDeUqTg
      - ACEISS_API_ENDPOINT=http://192.168.56.1:4318/
      - JAVA_OPTS=-javaagent:/agent/aceiss-javaagent-1.0.jar

  otel-collector:
#    image: https://github.com/aceiss/collector/blob/main/release/aceiss-collector-windows-0.61.0.exe:latest
    image: aceiss/collector:latest
    command: [ "--config=/etc/config.yml" ]
    volumes:
      - ./config.yml:/etc/config.yml
    ports:
      - "4318:4318"


